name: open62541_bindings
description: Bindings to the open62541 library.
version: 0.0.0-dev.1
repository: https://github.com/omarhogni/open62541_bindings

environment:
  sdk: ^3.3.0-82.0.dev
dependencies:
  binarize: ^2.0.0
  collection: ^1.19.1
  ffi: ^2.1.2
  logger: ^2.5.0
platforms:
  linux:
topics:
  - network
  - industrial
  - opcua
  - open62541
  - hmi
dev_dependencies:
  ffigen: ^12.0.0
  lints: ^4.0.0
  test: ^1.24.0
ffigen:
  output: lib/src/generated/open62541_bindings.dart
  name: open62541
  description: Low level bindings to open62541
  headers:
    entry-points:
      - 'open62541_build/open62541.h'
  functions:
    symbol-address:
      include:
        - 'UA_*' # Do this to expose all function pointers.
  # UA_TYPES is a list inside the library and we need raw access
  # To the top level pointer to increment the list.
  globals:
    symbol-address:
      include:
        - 'UA_TYPES'
  compiler-opts:
    - '-Iopen62541_build/install/include/'
    - '-I/lib/clang/19/include/'
    - '-Wno-nullability-completeness'
    - '-Wno-expansion-to-defined'
