name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed . # Line length is set in analysis_options.yaml

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Install dependencies for open62541 library Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libmbedtls-dev

      - name: Install dependencies for open62541 library macOS
        if: matrix.os == 'macos-latest'
        run: brew install mbedtls

      - name: Build open62541 library
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: ./open62541_tooling/build_lib.sh

      - name: Run tests
        run: dart test
