name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed . # Line length is set in analysis_options.yaml

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Build open62541 library
        run: |
          sudo apt install libmbedtls-dev
          ./build_lib.sh

      - name: Run tests
        run: dart test
